### ISSUE TITLE
Fix Formatting

### ISSUE THREAD

**Issue by je-el** [LisaJacklin/CS311#1]
https://github.com/LisaJacklin/CS311/blob/6c5aa0d3417b8832463f005a7116df959dd5600a/Homework/HW3/da3.cpp#L32
https://github.com/LisaJacklin/CS311/blob/6c5aa0d3417b8832463f005a7116df959dd5600a/Homework/HW3/da3.cpp#L33
https://github.com/LisaJacklin/CS311/blob/6c5aa0d3417b8832463f005a7116df959dd5600a/Homework/HW3/da3.cpp#L15
https://github.com/LisaJacklin/CS311/blob/6c5aa0d3417b8832463f005a7116df959dd5600a/Homework/HW3/da3.cpp#L16
Try fixing your formatting here and in similar places, rather than using new line for functions.

**Comment by LisaJacklin** [comment]
Adjusted to make the functions single lines for easy reading!
